# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20180310_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='users',
            field=models.ManyToManyField(related_name='quotes', to='quotes.User'),
        ),
    ]
